### ISSUE TITLE
如何查看已上传的文件链接？

### ISSUE THREAD

**Issue by yang9w** [sxyazi/free-hls#10]
如何查看已上传的文件链接？
或者查询。是不是链接丢了就无法找回了？

**Comment by sxyazi** [comment]
上传成功链接会打印在终端。或者在全部上传完成后在 `tmp/out.m3u8` 中查看。

在视频上传完成后，整个 `out.m3u8` 文件都会提交给服务端保存，只要服务端还能正常运行，数据就不会丢失。
