### ISSUE TITLE
建议添加已上传文件的索引

### ISSUE THREAD

**Issue by widsnoy** [sxyazi/free-hls#13]
不方便查看上传过的文件，建议在网站上添加文件索引显示已上传视频的名称与地址。

**Comment by sxyazi** [comment]
这涉及到另外一个问题，有些视频可能是私密的，只有拿到视频 KEY 的人才有权观看，如果全部列出来这种私密性会丧失。

**Comment by a77uu** [comment]
能不能..把video.js引用cdn.jsdelivr.net的CDN，这样访问起来会更快。
https://cdn.jsdelivr.net/npm/video.js@7.6.6/dist/video-js.css
https://cdn.jsdelivr.net/npm/video.js@7.6.6/dist/video-js.min.css
https://cdn.jsdelivr.net/npm/videojs-hotkeys@0.2.25/videojs.hotkeys.js

**Comment by widsnoy** [comment]
> 这涉及到另外一个问题，有些视频可能是私密的，只有拿到视频 KEY 的人才有权观看，如果全部列出来这种私密性会丧失。

可以在上传时设置权限吗？

**Comment by sxyazi** [comment]
> 可以在上传时设置权限吗？

如果是单独搞个文件用来列出目录呢，比如 `ls.py` 这样。

**Comment by widsnoy** [comment]
> > 可以在上传时设置权限吗？
> 
> 如果是单独搞个文件用来列出目录呢，比如 `ls.py` 这样。

这样也能达到目的，最好还能显示文件的名称，谢谢！
