### ISSUE TITLE
服务端问题

### ISSUE THREAD

**Issue by mrzhaoer** [sxyazi/free-hls#14]
服务端启动后，不知道过多长时间就不能访问了，就得把后台杀掉，再重新启动，然后过段时间又不能访问。。

**Comment by sxyazi** [comment]
使用什么命令启动的？大概多久出现一次？

**Comment by mrzhaoer** [comment]
gunicorn app:app -b 0.0.0.0:3395 --workers=5 --threads=2 -D


就是这个啊。 具体多久也不清楚，睡一觉起来就不能访问了。

就得kill掉进程，再开启一遍。。

**Comment by mrzhaoer** [comment]
[http://puui.qpic.cn/fans_admin/0/3_154798165_1583409751205/0](url)

**Comment by sxyazi** [comment]
`ps aux | grep gunicorn` 看下进程还在吗

**Comment by mrzhaoer** [comment]
等下班回去看看。

**Comment by mrzhaoer** [comment]
https://s2.ax1x.com/2020/03/06/3bAMf1.png

运行过后的 截图。

**Comment by sxyazi** [comment]
我看了你的图片，gunicorn 运行似乎正常。应该不是 gunicorn 造成的问题。我这边测试没出现过这种情况。
