### ISSUE TITLE
客户端问题！！！！

### ISSUE THREAD

**Issue by wzw1wzw** [sxyazi/free-hls#15]
客户端使用的是centos系统
   视频上传到/www 里了  视频也改成test.mp4了
 输入命令python3 up.py ~/www/test.mp4
 提示  FileNotFoundError: [Errno 2] No such file or directory: 'ffprobe': 'ffprobe'
   请问一下怎么解决啊。。

**Comment by sxyazi** [comment]
找不到 ffprobe 文件。检查下是否正确安装了 ffmpeg，如果是编译安装是否配置了正确的环境变量。
