### ISSUE TITLE
语雀已经凉了

### ISSUE THREAD

**Issue by sxyazi** [sxyazi/free-hls#19]
刚才语雀网站看了下，之前绕过语雀流量的方法已经失效了，现在上传文件（包括传头像）都会计流量了，估计是被玩怕了。

至此语雀算是基本废了。以后的路有4条：
1. 继续使用语雀，多账号轮换，每个账号有10G流量。可以多注册点账号，目前注册账号还没门槛（只有短信验证码，找验证码平台）；
2. （不推荐，要钱）继续使用语雀，开个会员，首年59。有100G流量可用；
3. （推荐）自己找新的图床，在 uploader 目录添加新的图床上传脚本；
4. 上传到自己服务器（后面会加本地上传支持）；

说一下我的想法，我比较推荐第 3 种方法，因为本身免费视频床就是利用各大平台的 BUG 实现的。如果这一 BUG 被公布了出来，那么很快就凉了。所以我推荐把本程序当作是一个集成化的视频切片、上传、分享工具，至于往哪里传自己找图床，自己用也不要公开。

图床这个东西个人感觉还是不难找的，找国内比较大的平台，然后在里面找上传图片/文件的界面，抓个包就有了。对于上传限制可以通过伪造 Content-Type 和 文件头 来绕过，一般都是没啥难度的。不过最终的图片网址必须是支持 CORS 跨域的才行，具体看 Response Body 里面有没有 `Access-Control-Allow-Origin: *` 属性。

**Comment by VegeHime** [comment]
不光凉了 而且图片大小限制变低了 现在是10M

**Comment by x91270** [comment]
能不能控制切片5M 以下呢？

**Comment by sxyazi** [comment]
> 能不能控制切片5M 以下呢？

默认情况下程序会自动计算切片时长以满足上传条件，也可以使用第3个参数手动指定切片时长。对于码率较高的视频使用 LIMITED 模式。

**Comment by yzzk** [comment]
能加一个换IP的功能吗，换IP的话 以前上传的就没了

**Comment by x91270** [comment]
> > 能不能控制切片5M 以下呢？
> 
> 默认情况下程序会自动计算切片时长以满足上传条件，也可以使用第3个参数手动指定切片时长。对于码率较高的视频使用 LIMITED 模式。

我测试了。实际还是有上传失败

**Comment by TheEnd233** [comment]
请问能更新一下readme吗，视频教程好像已经过时了

**Comment by hanjianlin** [comment]
补充一下   可以这样设定 5M 以下 上传到 阿里爸爸  5-10M 上传到云雀  这样 流量可以合理利用

**Comment by qq165529094** [comment]
大佬 ，可以修改一下，把切片上传到github仓库嘛，毕竟每个人都有自己的仓库。通过API上传到自己的仓库，然后通过JSdelivr免费CDN获取，这样速度还快。 希望考虑一下。

**Comment by fengmk2** [comment]
围观

**Comment by bobodeng** [comment]
·-· 我愿称之为「图床果实-幻兽种-四分五裂形态」

**Comment by sxyazi** [comment]
@fengmk2 @bobodeng 恐怖，是语雀的大佬🙀
