### ISSUE TITLE
你好，请问注册雨雀是做什么用的

### ISSUE THREAD

**Issue by jc91715** [sxyazi/free-hls#2]

**Comment by lengthmin** [comment]
把视频切片后，上传到语雀的cdn

**Comment by sxyazi** [comment]
语雀是阿里旗下的一款在线协同办公平台，
语雀提供了上传文件的功能， free-hls 的视频是上传到语雀的，后面可能还会增加其他的平台支持。
由于传到了阿里，所以播放视频不耗费你机器的流量。并且国内用户的速度能得到相对稳定的保障。
