### ISSUE TITLE
限制码率还是出现部分切片大于5M的问题

### ISSUE THREAD

**Issue by TheEnd233** [sxyazi/free-hls#21]
## 概述

使用命令
python up.py "【泪目向Flower Dance】鸠子：中二是什么？我不明白啊！ - 1.1(Av1731928,P1).mp4" LIMITED
进行切片后还是有出现部分切片文件大于5M
[aac @ 00000277eb96b080] Qavg: 1585.722
File too large: tmp/out00009.ts

**Comment by sxyazi** [comment]
你用的是阿里图床吗？那个限制比较大，建议找其他图床更换。
图床还是蛮好找的，今天就找到好几个（

**Comment by Harry-Wen** [comment]
我有相同的问题，明明设置了LIMITED却还是有的超过了5M

**Comment by sxyazi** [comment]
@Harry-Wen 贴一下完整输出，LIMITED 模式早在 2020 年就已经废弃了（见 https://github.com/sxyazi/free-hls/commit/e14e4b649386b80d2a4c7249d2e19a8ee01ff73d 这个提交），取而代之的是更好的 2-pass 模式。

**Comment by Harry-Wen** [comment]
> @Harry-Wen下一次完整输出，LIMITED 早在 2020 年就已经退出模式（见[e144b6](https://github.com/sxyazi/free-hls/commit/e14e4b649386b80d2a4c7249d2e19a8ee01ff73d)这个提交），取而代之是更好的 2-pass 模式。

解决了是我压制的问题，关键帧设置太高
