### ISSUE TITLE
视频是存在哪里的？服务器还是语雀？

### ISSUE THREAD

**Issue by AndersonHJB** [sxyazi/free-hls#26]
视频是存在哪里的？服务器还是语雀？

**Comment by sxyazi** [comment]
视频上传和存储，取决于你的上传驱动器（uploader）是什么，如果使用`local` 驱动器，则是存储在 server。

更多请参考 [上传驱动器](https://github.com/sxyazi/free-hls/wiki/%E4%B8%8A%E4%BC%A0%E9%A9%B1%E5%8A%A8%E5%99%A8) 文档。
