### ISSUE TITLE
上传成功了，但是播放一直在转圈

### ISSUE THREAD

**Issue by zgll** [sxyazi/free-hls#27]
看浏览器的请求好像是跨域的问题，能解决的吗

http://ycy.yaoyaoling.net:33950/playlist/1?watch=c2c2d681a9aacea6

**Comment by sxyazi** [comment]
跨域是浏览器安全策略限制，没法绕过去，换个支持跨域的图床，[参见相关文档](https://github.com/sxyazi/free-hls/wiki/%E4%B8%8A%E4%BC%A0%E9%A9%B1%E5%8A%A8%E5%99%A8)
