### ISSUE TITLE
客户端报错 

### ISSUE THREAD

**Issue by kkaaas** [sxyazi/free-hls#29]
[root@CentOS-79-64-minimal ]# python3 up.py 5.mp4
Traceback (most recent call last):
  File "up.py", line 7, in <module>
    from utils import (api,exec, execstr, tsfiles, uploader,
ImportError: cannot import name 'api'

**Comment by sxyazi** [comment]
先切换到目录里再运行，确保当前目录有 `utils.py` 文件。我这边最新 Python 3.10.8 测试运行正常。
