### ISSUE TITLE
.m3u8播放地址使用其他外部播放器播放问题

### ISSUE THREAD

**Issue by dahai4567** [sxyazi/free-hls#6]
得到的m3u8播放连接，放在外部播放器中无法播放，是需要配置跨域还是其他的操作，请教一下

**Comment by sxyazi** [comment]
外部播放器指的是网页浏览器还是桌面浏览器呢？如果是网页尝试在 HTML 头部添加如下代码：
```html
<meta name="referrer" content="no-referrer">
```

**Comment by dahai4567** [comment]
比如一下videojs后者dPlayer等播放器 好像桌面播放器vlc也是不可以的昂

**Comment by dahai4567** [comment]
获取m3u8文件失败(manifestLoadError)


code：4006

uuid:07A55219-B14F-4903-AD58-FDA51483E977

requestId:178C62C7-20B5-4C43-BAFF-19E59BD52BFF

使用阿里云云播诊断结果如上

**Comment by sxyazi** [comment]
方便发出你的视频地址吗，我看一下

**Comment by dahai4567** [comment]
你好 
地址为https://play.ziyou.best/play/2a6a993a9b357a338b37e6a6b2d25f3f.m3u8

**Comment by sxyazi** [comment]
这个是由于客户端与服务端版本不一致造成的，你需要把服务端的程序升级为最新然后重新上传此视频

**Comment by dahai4567** [comment]
好的 谢谢大佬
