### ISSUE TITLE
使用外部播放器播放.m3u8文件一直失败

### ISSUE THREAD

**Issue by dahai4567** [sxyazi/free-hls#7]
你好 ，我生成的.m3u8文件可以下载，然后打开发现不是ts格式都是png格式 这个是不是博主你做了伪装，现在问题就是使用vlc或者dplayer播放器都是无法播放的，
<source src="data:application/vnd.apple.mpegurl;base64,{{meta.code}}"
type="application/vnd.apple.mpegurl">
这个是你播放器中的写法 
http://173.82.243.24:3395/play/af3e9c0515249f8f.m3u8 
http://173.82.243.24:3395/play/af3e9c0515249f8f
博主你帮我看下 ，为什么我的.m3u8无法播放

**Comment by sxyazi** [comment]
不是伪装，视频是用的阿里图片接口传的，所以就是png格式。我这边使用 IINA，VLC 测试这个地址都能正常播放。

**Comment by dahai4567** [comment]
博主我这边是使用vlc media player无法播放，我看了一下下载下来的m3u8文件，里面不是ts文件 都是png文件 ，我在想播放到时候不需要转成ts嘛 ，你的代码里面是通过base64加密然后再播放器中解密的方式  这个是使用m3u8播放器 还是hls播放器 我感觉越来越糊涂了 哈哈

**Comment by dahai4567** [comment]
博主你好 我想加一下你的qq 你加我吧 3491441506

**Comment by sxyazi** [comment]
m3u8 是 HLS 的播放列表，ts 里面是实际的视频，这里是利用阿里的**图片**接口把视频当作图片上传上去了，所以文件名是 png 结尾的。但是这并不影响播放

**Comment by dahai4567** [comment]
你好 https://www.m3u8play.com/?play=https://173.82.243.24:3395/play/af3e9c0515249f8f.m3u8
就是这样，无法播放 ，我在本地vlc测试也不行，你看下

**Comment by sxyazi** [comment]
你的网址 https://173.82.243.24:3395/play/af3e9c0515249f8f.m3u8 不能打开

**Comment by dahai4567** [comment]
你好你可以给我一个你的测试视频播放地址嘛 我这边测试一下

**Comment by dahai4567** [comment]
http://173.82.243.24:3395/play/af3e9c0515249f8f.m3u8
http://173.82.243.24:3395/play/af3e9c0515249f8f 
我这的两个地址都是可以访问的

**Comment by sxyazi** [comment]
我这边测试使用 IINA，VLC 都可以正常播放，使用的是 http://173.82.243.24:3395/play/af3e9c0515249f8f.m3u8 这个地址。如果你需要在其他网页播放（非 http://173.82.243.24:3395/play/af3e9c0515249f8f），需要对应的网页添加了 `<meta name="referrer" content="no-referrer">` 标签。最新的代码解决了跨域播放问题，可以使用 git pull 命令更新一下。

<img width="946" alt="Snipaste_2020-02-26_19-16-17" src="https://user-images.githubusercontent.com/17523360/75339983-8370c580-58cc-11ea-9997-982e12d01ef7.png">

**Comment by dahai4567** [comment]
你好 博主 我重新拉了一下 现在在测试 但是切片的时候遇到了 Publish failed: network connection error
这个问题 ，服务端可以访问返回helloword 同时.env中 配置都是正确的 我是使用ip地址 所以我就是APIURL=http://173.82.243.24:3395,

**Comment by sxyazi** [comment]
客户端也同时需要更新

**Comment by dahai4567** [comment]
你好 我从地址新拉了代码 ，然后外部播放器还是播放不了 大佬你看下
播放地址为：
http://173.82.243.24:3395/play/ac2a2b0d8fe9ba5d
http://173.82.243.24:3395/play/ac2a2b0d8fe9ba5d.m3u8
![3](https://user-images.githubusercontent.com/38673156/75347362-8aeb9b00-58db-11ea-84ee-581f9ebb5733.png)

**Comment by sxyazi** [comment]
这个是他网站没加 meta 头。参照 https://github.com/sxyazi/free-hls/issues/7#issuecomment-591375764

**Comment by dahai4567** [comment]
你好 这个问题解决了 谢谢大佬哈 感谢 ，现在就是有一个新的问题就是，如果切片的视频文件比较大，
例如2G左右 就会返回none 和none.m3u8 这个怎么解决呀  我猜是不是<src:data 这种方式字段存储不了这么大的类型 还是其他的问题导致的

**Comment by sxyazi** [comment]
方便把视频发出来给我测试一下吗，或者提供一下报错？

**Comment by dahai4567** [comment]
![微信截图_20200226225052](https://user-images.githubusercontent.com/38673156/75356168-82e72780-58ea-11ea-87ad-72262200700a.png)

**Comment by dahai4567** [comment]
![00](https://user-images.githubusercontent.com/38673156/75356374-d48fb200-58ea-11ea-8a13-f8c919a5b95b.png)

**Comment by dahai4567** [comment]
大概2个多g的视屏 你给我的那个上传不了 有限制
视频格式是flv的

**Comment by dahai4567** [comment]
问题我猜应该是你的源码里面使用了code传递ts信息，当ts比较多的时候 估计code无法存储了

**Comment by sxyazi** [comment]
已经增加最大代码限制到 500K 了 https://github.com/sxyazi/free-hls/commit/5e304b6eac1534f96e549336af9c0489d46cd1e2

**Comment by dahai4567** [comment]
好的谢谢大佬 那我是不是要把服务端和客户端代码重新拉一下

**Comment by sxyazi** [comment]
> 好的谢谢大佬 那我是不是要把服务端和客户端代码重新拉一下

对

**Comment by dahai4567** [comment]
![5](https://user-images.githubusercontent.com/38673156/75357891-09046d80-58ed-11ea-8fdf-f181411a2c1d.png)

**Comment by sxyazi** [comment]
重新 pull 服务端，重启服务

**Comment by dahai4567** [comment]
好的 谢谢大佬
