### ISSUE TITLE
切片设置 1 也无法上传

### ISSUE THREAD

**Issue by vpsbash** [sxyazi/free-hls#8]
https://pic.i1.yt/images/2020/02/27/powershell_FSDlwDFM3N.png

切片参数是1 文件大小还是超过了20M 有什么办法吗

https://pic.i1.yt/images/2020/02/27/explorer_3aHkYiVhvk.png

**Comment by sxyazi** [comment]
视频是什么格式的？分辨率多少？尝试使用码率限制模式：
```bash
python3 up.py test.mp4 标题 LIMITED
```
