### ISSUE TITLE
请问语雀上传应该限制流量吧？

### ISSUE THREAD

**Issue by noiraimer** [sxyazi/free-hls#9]
个人免费版不是限制10G上传流量吗？请问您的没有限制吗？

**Comment by sxyazi** [comment]
有流量限制，但是 free-hls 上传的没有。具体看图
<img width="844" alt="Snipaste_2020-02-29_21-14-29" src="https://user-images.githubusercontent.com/17523360/75608228-a8697080-5b38-11ea-9af9-d108f54721dc.png">

（这个账号至今为止应该也上传了三四十G的视频了，但语雀后台看流量还是0，那个0.06是我之前测试拿浏览器上传的）

**Comment by noiraimer** [comment]
> 
> 
> 有流量限制，但是 free-hls 上传的没有。具体看图
> <img alt="Snipaste_2020-02-29_21-14-29" width="844" src="https://user-images.githubusercontent.com/17523360/75608228-a8697080-5b38-11ea-9af9-d108f54721dc.png">
> 
> （这个账号至今为止应该也上传了三四十G的视频了，但语雀后台看流量还是0，那个0.06是我之前测试拿浏览器上传的）

谢谢解答😁

**Comment by yang9w** [comment]
一不小心撸翻车了就麻烦了
